import { PipelineConfig } from '../pipeline/types';

export const baseConfig: Omit<PipelineConfig, 'city' | 'bounds'> = {
  targetCount: 150,
  resolution: 15,
  types: [
    'restaurant',
    'cafe',
    'bar',
    'liquor_store',
    'tourist_attraction',
    'amusement_park',
    'aquarium',
    'art_gallery',
    'movie_theater',
    'museum',
    'night_club',
    'park',
    'zoo',
    'stadium',
    'church',
    'mosque',
    'synagogue',
    'shopping_mall',
    'cemetery',
    'library',
    'campground',
  ],
  stages: [
    { name: 'place_fetching', enabled: true, params: { delayMs: 125 } },
    { name: 'name_similarity_dedup', enabled: true, params: { threshold: 0.85 } },
    { name: 'proximity_dedup', enabled: true, params: { thresholdMeters: 50 } },
    { name: 'rating_threshold', enabled: true, params: { minReviews: 5 } },
    { name: 'generic_filter', enabled: true },
    {
      name: 'category_quotas',
      enabled: true,
      params: {
        maxPlaces: 500,
        defaultWeight: 0.5,
        quotas: [
          { typeName: 'museum', threshold: 1.0, weight: 1.0, neverRemove: true },
          { typeName: 'church', threshold: 1.0, weight: 1.0, neverRemove: true },
          { typeName: 'synagogue', threshold: 1.0, weight: 1.0, neverRemove: true },
          { typeName: 'mosque', threshold: 0.1, weight: 1.0, neverRemove: false },
          { typeName: 'tourist_attraction', threshold: 0.7, weight: 1.0, neverRemove: true },
          { typeName: 'amusement_park', threshold: 0.5, weight: 0.9, neverRemove: false },
          { typeName: 'aquarium', threshold: 0.9, weight: 0.9, neverRemove: false },
          { typeName: 'zoo', threshold: 0.9, weight: 0.9, neverRemove: false },
          { typeName: 'art_gallery', threshold: 0.4, weight: 0.9, neverRemove: false },
          { typeName: 'movie_theater', threshold: 0.6, weight: 0.8, neverRemove: false },
          { typeName: 'night_club', threshold: 0.7, weight: 0.8, neverRemove: false },
          { typeName: 'park', threshold: 0.4, weight: 0.9, neverRemove: false },
          { typeName: 'campground', threshold: 0.5, weight: 0.7, neverRemove: false },
          { typeName: 'restaurant', threshold: 0.1, weight: 0.7, neverRemove: false },
          { typeName: 'cafe', threshold: 0.1, weight: 0.7, neverRemove: false },
          { typeName: 'bar', threshold: 0.3, weight: 0.7, neverRemove: false },
          { typeName: 'liquor_store', threshold: 0.2, weight: 0.5, neverRemove: false },
          { typeName: 'shopping_mall', threshold: 0.4, weight: 0.7, neverRemove: false },
          { typeName: 'stadium', threshold: 0.6, weight: 0.7, neverRemove: false },
          { typeName: 'library', threshold: 0.2, weight: 0.7, neverRemove: false },
          { typeName: 'cemetery', threshold: 0.05, weight: 0.3, neverRemove: false },
        ],
      },
    },
    { name: 'llm_ranking', enabled: true },
  ],
};
