import { PipelineConfig } from '../pipeline/types';
import { baseConfig } from './base';

export const pragueConfig: PipelineConfig = {
  ...baseConfig,
  city: 'Prague',
  bounds: {
    north: 50.15,
    south: 50.00,
    east: 14.55,
    west: 14.25,
  },
  stages: [
    { name: 'place_fetching', enabled: true, params: { delayMs: 125 } },
    { name: 'name_similarity_dedup', enabled: true, params: { threshold: 0.85 } },
    { name: 'proximity_dedup', enabled: true, params: { thresholdMeters: 50 } },
    { name: 'rating_threshold', enabled: true, params: { minReviews: 5 } },
    {
      name: 'generic_filter',
      enabled: true,
      params: {
        blacklistedTypes: [
          'gas_station',
          'car_wash',
          'car_repair',
          'dental_clinic',
          'dentist',
          'doctor',
          'hair_salon',
          'barber_shop',
          'consultant',
          'corporate_office',
          'government_office',
          'shipping_service',
          'real_estate_agency',
          'veterinary_care',
          'pet_boarding_service',
          'pet_care',
          'hospital',
          'school',
          'university',
          'building_materials_store',
          'furniture_store',
          'parking_lot',
          'parking',
          'transit_station',
        ],
        namePatterns: [
          /^Cemetery$/i,
          /^Park$/i,
          /^dog park$/i,
          /^Entrance \d+$/i,
          /školní/i,
        ],
      },
    },
    {
      name: 'category_quotas',
      enabled: true,
      params: {
        maxPlaces: 500,
        defaultWeight: 0.5,
        quotas: [
          { typeName: 'museum', threshold: 1.0, weight: 0.6, neverRemove: false },
          { typeName: 'church', threshold: 0.45, weight: 0.65, neverRemove: false },
          { typeName: 'synagogue', threshold: 0.6, weight: 1.0, neverRemove: true },
          { typeName: 'mosque', threshold: 0.1, weight: 1.0, neverRemove: false },
          { typeName: 'tourist_attraction', threshold: 1.0, weight: 0.9, neverRemove: true },
          { typeName: 'amusement_park', threshold: 0.0, weight: 0.9, neverRemove: false },
          { typeName: 'aquarium', threshold: 0.9, weight: 0.9, neverRemove: false },
          { typeName: 'zoo', threshold: 0.9, weight: 0.9, neverRemove: false },
          { typeName: 'art_gallery', threshold: 1.0, weight: 0.9, neverRemove: false },
          { typeName: 'movie_theater', threshold: 0.8, weight: 0.8, neverRemove: false },
          { typeName: 'night_club', threshold: 1.0, weight: 0.9, neverRemove: true },
          { typeName: 'park', threshold: 0.15, weight: 0.9, neverRemove: false },
          { typeName: 'campground', threshold: 0.5, weight: 0.7, neverRemove: false },
          { typeName: 'restaurant', threshold: 0.125, weight: 0.6, neverRemove: false },
          { typeName: 'cafe', threshold: 0.3, weight: 0.7, neverRemove: false },
          { typeName: 'bar', threshold: 0.6, weight: 0.7, neverRemove: false },
          { typeName: 'liquor_store', threshold: 0.05, weight: 0.6, neverRemove: false },
          { typeName: 'shopping_mall', threshold: 0.1, weight: 0.7, neverRemove: false },
          { typeName: 'stadium', threshold: 0.4, weight: 0.7, neverRemove: true },
          { typeName: 'library', threshold: 0.05, weight: 0.7, neverRemove: false },
          { typeName: 'cemetery', threshold: 0.05, weight: 0.3, neverRemove: false },
        ],
      },
    },
    { name: 'llm_ranking', enabled: true, params: { model: 'deepseek-v4-flash' } },
  ],
};
