export const FOG_CONFIG = {
  FOG_CLEAR_RADIUS_CELLS: 6,
  POI_HINT_RADIUS_METERS: 200,
  POI_DISCOVER_RADIUS_METERS: 65,
  SYNC_COALESCE_MS: 1500,
  LOCATION_UPDATE_INTERVAL_MS: 2000,
  LOCATION_UPDATE_DISTANCE_M: 5,
  BACKGROUND_LOCATION_INTERVAL_MS: 12000,
  BACKGROUND_LOCATION_DISTANCE_M: 15,
} as const;

export const VISION_CONFIG = {
  RADIUS_METERS: 100,
  HALF_ANGLE_DEG: 25,
  LEAD_DISTANCE_M: 0,
  BANDS: 4,
  OPACITY: 0.08,
} as const;
