export const FOG_CONFIG = {
  FOG_CLEAR_RADIUS_CELLS: 6,
  POI_HINT_RADIUS_METERS: 150,
  POI_DISCOVER_RADIUS_METERS: 35,
  SYNC_INTERVAL_MS: 3000,
  LOCATION_UPDATE_INTERVAL_MS: 2000,
  LOCATION_UPDATE_DISTANCE_M: 5,
} as const;
